// THIS IS AUTOGENERATED FILE DAWG
import {IEntity, Snapshot, SISchema, InterpolatedSnapshot} from "./Common.js"
import Lerp from "./Lerp.js"
import SnapshotInterpolation from "./SnapshotInterpolation.js"
import SnapshotPool from "./SnapshotPool.js"
import Vault from "./Vault.js"
const SI = {
  IEntity,
  Snapshot,
  SISchema,
  InterpolatedSnapshot,
  Lerp,
  SnapshotInterpolation,
  SnapshotPool,
  Vault,
}
export default SI